### ISSUE TITLE
@pyimport numpy fails

### ISSUE THREAD

**Issue by ufechner7** [stevengj/PyCall.jl#65]
Hello,
I use Ubuntu 12.04, 64 bit. I installed numpy 1.7.1 with pip.

Importing numpy fails:

julia> using PyCall

julia> @pyimport numpy
ERROR: PyError (PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('cannot import name scimath',)
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath

 in pyerr_check at /home/ufechner/.julia/PyCall/src/exception.jl:58
 in pyimport at /home/ufechner/.julia/PyCall/src/PyCall.jl:85

Importing numpy from python works fine, importing other packages from julia
also works.

Any idea?

Uwe Fechner

**Comment by cberzan** [comment]
@stevengj The issue appears to be about circular imports. Here is how they are supposed to work: http://stackoverflow.com/a/744403/744071

To demonstrate the issue: Make a virtualenv and install numpy==1.9.1. Then go to where it was installed, and add the following line near the top of `numpy/__init__.py`: `print("numpy.__init__ running")`. Add a similar line to the files `numpy/lib/__init__.py` and `numpy/lib/scimath.py`. Now, if you run this from python:

```
>>> import numpy
numpy.__init__ running
numpy.lib.__init__ running
numpy.lib.scimath running
```

That looks good. Now run the same from julia (v0.3.2) using PyCall (version 0.7.3):

```
julia> using PyCall
julia> @pyimport numpy
numpy.__init__ running
numpy.lib.__init__ running
numpy.lib.scimath running
numpy.__init__ running
numpy.lib.__init__ running
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('cannot import name scimath',)
  File "/home/cberzan/.virtualenvs/captcha/local/lib/python2.7/site-packages/numpy/__init__.py", line 172, in <module>
    from . import add_newdocs
  File "/home/cberzan/.virtualenvs/captcha/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/cberzan/.virtualenvs/captcha/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 19, in <module>
    from . import scimath as emath

 in pyerr_check at /home/cberzan/.julia/v0.3/PyCall/src/exception.jl:58
 in pyimport at /home/cberzan/.julia/v0.3/PyCall/src/PyCall.jl:91
```

As you can see, the line `numpy.__init__ running` is printed twice, which shows that the circular imports aren't working properly.

I don't know enough about Python's import mechanism to debug this further, but I hope it leads you to a solution.

Update: Things get weirder. Consider this:

a.py:

```
print "a.py top"
import b
print "a.py bottom"
```

b.py:

```
print "b.py top"
import a
print "b.py bottom"
```

If I run this from the python shell, things work as expected:

```
>>> import a
a.py top
b.py top
b.py bottom
a.py bottom
```

But if I run it as a script, it does something else (I don't understand why):

```
$ python a.py
a.py top
b.py top
a.py top
a.py bottom
b.py bottom
a.py bottom
```

And Julia / PyCall behaves like the former:

```
$ PYTHONPATH="." julia
julia> using PyCall
julia> @pyimport a
a.py top
b.py top
b.py bottom
a.py bottom
```

So in this case Julia / PyCall seems to handle the circular imports properly.

**Comment by stevengj** [comment]
My first guess is that you have multiple versions of numpy etc. installed and it is getting confused about which one to import...

**Comment by stevengj** [comment]
The thing is, it is not PyCall that is "handling" the circular imports.  PyCall just calls `PyImport_ImportModule` from the CPython API, and the rest is done by CPython (the same as in `python`).  I can only think that is some path or environment variable that is making Python behave differently in PyCall.

**Comment by stevengj** [comment]
Can you try `__import__` in Python instead ([see here](http://stackoverflow.com/questions/7998816/do-pyimport-importmodule-and-import-statement-load-into-different-namespace)).

**Comment by cberzan** [comment]
@stevengj I found the cause of the problem.

First I realized that `sys.modules['numpy']` gets overwritten:

```
julia> using PyCall
julia> @pyimport numpy
numpy.__init__ running
id(sys.modules) = 89034704
id(sys.modules['numpy']) = 161528304
numpy.__init__ running
id(sys.modules) = 89034704
id(sys.modules['numpy']) = 177135864
```

Then I realized that `numpy` gets imported by PyCall even when I don't ask for it:

```
julia> using PyCall
julia> @pyimport datetime
numpy.__init__ running
...
```

The culprit is the line `pyimport("numpy")["ufunc"]` in the function `pyinitialize`. It appears to import numpy before the python interpreter is fully initialized (?), causing this weird issue. I don't know how to fix it properly, but as a workaround, I can just comment out the `ufuncType` global from `pyinitialize`.

BTW, if anyone is getting `ImportError("...../lib/julia/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /usr/lib/liblapack.so.3gf)",)`, a solution that worked for me is to invoke julia with `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3 julia`. This loads the system `libgfortran` instead of the one bundled with julia.

Yay, I can finally use PyPlot from julia!

**Comment by stevengj** [comment]
Thanks for looking into this.  (The need for the numpy ufunc thing will go away in Julia 0.4; see #101.)

However, I don't understand the problem, since Python has been initialized when the `pyimport("numpy")["ufunc"]` is called.  

Could it possibly be that Python is reloading the `numpy` module because it got garbage-collected?  i.e. `pyimport("numpy")["ufunc"]` loads the module and stores a reference in a temporary object, which Julia will eventually free.  When Julia frees the object, the corresponding module reference in Python is decrementing, which I suppose tells Python it is okay to unload the module.  Then later on when you import `numpy` again, Python reloads it, and somehow this goes horribly wrong?   If this is the problem, a simple workaround would be to modify `pyinitialize` to store the `numpy` reference in a global constant so that it is never garbage-collected:

```julia
        global const numpy_module = try
            pyimport("numpy")
	catch
            PyObject() # NumPy not available                                    
        end
        global const ufuncType = numpy_module.o == C_NULL ? PyObject() : numpy_module["ufunc"]
```

(I'm not sure if anything can be done about the libgfortran thing; it's always a problem to have multiple incompatible Fortran compilers on your system; you have to be very careful about consistently linking the same one.)

**Comment by cberzan** [comment]
@stevengj I take back everything I said; it was a red herring. I just realized that `libgfortran` was at fault all along. If I `LD_PRELOAD` the correct version as I mentioned above, then `@pyimport numpy` works fine with an unmodified version of PyCall (i.e. without doing anything about `ufuncType`). I guess the lesson here is that if there's a problem with a `.so` file, python's import mechanism fails horribly and with completely misleading error messages...

**Comment by mlubin** [comment]
Also ran into this, ``LD_PRELOAD`` trick didn't fix it.

**Comment by jmxpearson** [comment]
Just to add to the documentation of this:

As of yesterday, running 04.-rc1 on my Ubuntu 14.10, I am having this issue. My particular version is that I cannot `pyimport("numpy")` (or anything that depends on NumPy). The `LD_PRELOAD` doesn't work for me either. No problem on my Mac (running latest OS X) with this. 

`PYTHONHOME` is set correctly as checked by `ccall`ing into libpython. 

Note that if I comment out the scimath import in `numpy/lib/__init__.py`, a similar error is raised in the next line when `polynomial` attempts to import from `numpy.core`. Anything I try to import *without* these relative package imports seems to be fine. Any import in Python/IPython also works.

**Comment by jmxpearson** [comment]
I will also note that a simple C version

```c
#include <Python.h>

int
main(int argc, char *argv[])
{
    PyObject *pModule;
    char *pName = "numpy";

    Py_Initialize();

    pModule = PyImport_ImportModule(pName);

    if (pModule != NULL) {
        printf("Success!\n");
    }
    else {
        PyErr_Print();
        fprintf(stderr, "Failed to load \"%s\"\n", pName);
        return 1;
    }
    Py_Finalize();

    return 0;
}
```

Runs successfully.

**Comment by holocronweaver** [comment]
Having same issue as @jmxpearson.

**Comment by jmxpearson** [comment]
Just for reference, I created a minimal Julia example that reproduces the issue. 

```
$ julia pyimport_test.jl json
```
works, while
```
$ julia pyimport_test.jl numpy
```
fails.

What could it be here, except `ccall`?

```julia
############## pyimport_test.jl ######################################
const stub = homedir() * "/anaconda"
const libname = @osx? "libpython2.7.dylib" : "libpython2.7.so"
const libpython = stub * "/lib/" * libname

################# from PyCall.jl #####################################
immutable PyObject_struct
    ob_refcnt::Int
    ob_type::Ptr{Void}
end

typealias PyPtr Ptr{PyObject_struct} # type for PythonObject* in ccall

macro pysym(func)
    :(($func, libpython))
end
################# from PyCall.jl #####################################

# now, do some ccalling to initialize

ccall((@pysym :Py_InitializeEx), Void, (Cint,), 0)

modname = ARGS[1] 
println("About to try loading library $modname")

modptr = ccall((@pysym :PyImport_ImportModule), PyPtr, (Ptr{Uint8},), 
    bytestring(modname))

if modptr == C_NULL
    println("Could not load library.")
else
    println("Success!")
end

ccall((@pysym :Py_Finalize), Void, ())
```

**Comment by stevengj** [comment]
@jmxpearson, I really think it is some Python path thingy that is missing; `ccall` is calling `libpython`, it is `PyImport_ImportModule` that is not succeeding.   See, for example, the persistent problems with Canopy (#42).   There is some mysterious path setting that seems to be needed in some Python distros, that I have yet to figure out.

(It sucks that the hardest thing about PyCall has been figuring out how to initialize Python correctly.)

**Comment by jmxpearson** [comment]
Agree. That really does seem like the most likely solution, except that PyCall is correctly inferring the location of libpython on my system, correctly setting PYTHONHOME, and having run the code more or less line by line, I can't find the failure until you try to import numpy for loading ufunc.

At every point where I have been able to interrogate path settings, they've been the same between my mac (working) and linux (not).

**Comment by ihnorton** [comment]
You could try setting `LD_DEBUG=all` before running the Julia script. This will be very noisy, but should tell you if there is some shared library loading error while attempting to import numpy. Call `LD_DEBUG=help cat` to see all of the options. (You may want to print some separator output at the start of your script so you can find where the Julia initialization ends)

**Comment by jmxpearson** [comment]
Thanks @ihnorton. After combing through the output, I found that several symbols were coming up undefined. I think numpy is having trouble using julia's libopenblas, which I assume is overshadowing its own. If I do

```
LD_PRELOAD=$HOME/anaconda/lib/libopenblas.so julia pyimport_test.jl numpy
```

Everything works!

It appears that I'm having the same issue as cberzan above, just with a different shared library.

@stevengj, any ideas about a fix? Seems dicey to change anything based on circumventing julia's openblas build long-term.

**Comment by jmxpearson** [comment]
An additional note: the problem is not that the symbols numpy is looking for are missing from julia's libopenblas. Running nm shows that julia's version simply appends 64 to the ends of these symbols.

**Comment by stevengj** [comment]
@jxmpearson, Julia's openblas was patched to append `64` to its symbols (JuliaLang/julia#8734) precisely to avoid conflicting with numpy (JuliaLang/julia#4923).

It's a bit frustrating that we are still having problems with conflicts, but maybe it's sufficient to simply rename Julia's `openblas` library in a future version so that NumPy doesn't find it?

**Comment by stevengj** [comment]
@jmxpearson, when you say that you downgraded numpy, what was the version that didn't work and what version do you have now?  Or was it just a bug in anaconda?  I'm confused.

**Comment by jmxpearson** [comment]
@stevengj I had numpy 1.9.2-py27_1, which was replaced with 1.9.2.py27_0
Setuptools and pip were also changed. So if I ask conda to update numpy (reversing what I did), these are the proposed changes:

```
The following packages will be UPDATED:

    numpy:      1.9.2-py27_0  --> 1.9.2-py27_1
    pip:        7.0.3-py27_0  --> 7.1.2-py27_0
    setuptools: 17.1.1-py27_0 --> 18.1-py27_0 
```

I suspect that in trying to update numpy in hopes of clearing this up, I got it out of whack with something else in anaconda. It's also possible that updating anaconda as a whole fixed something else that I'm not seeing here.

re: renaming openblas: Seems like a tough thing to have to do if the only people who are having this problem are those with out of whack Python configurations, but if it's transparent to end users, perhaps it's worthwhile to avoid conflicting with other installs?

**Comment by stevengj** [comment]
Renaming the openblas library internal to Julia is easy, and shouldn't hurt anything else, if that actually solves the problem.

**Comment by jmxpearson** [comment]
Well, I guess if this problem keeps creeping up, it might be worth a go.

Thanks again!

**Comment by ttfoley** [comment]
I was referred here from  https://github.com/stevengj/PyCall.jl/commit/4b2732d5f35176e2bc84ce7db1e325e6ae949666,

for fear of messing things up, could someone please include instructions for "renaming openblas"?

Thank you, and apologies for my noobness.

**Comment by jmxpearson** [comment]
I think @stevengj means this is something that will change in Julia itself. 

In the meantime, `LD_PRELOAD` is probably the way to go. I have also been having some issues with PyPlot itself, but I think that's separate.

**Comment by ttfoley** [comment]
Thanks jmx!  Are you able to get any sort of plotting working using the preload?
Even why I do @pyimport matplotlib.pyplot as plt  for plotting, the kernel dies on me.
I'm also to the point where I might just save all of my data in some sort of python numpy form, and plot it in a separate notebook.

**Comment by jmxpearson** [comment]
I was able to `@pyimport` successfully, both with the `LD_PRELOAD` trick and once I did `conda update anaconda` above (different "fixes").

The plotting issue I have I'm still trying to pin down. I can do lots of plotting just fine, but have some reproducible crashes related to certain types of plots. I think this is really tied to garbage collection in PyCall, and will need to be separate issue there.

**Comment by ttfoley** [comment]
I see. I am able to do get everything to import successfully using the tricks, but my kernel dies everytime I try to plot anything.  This is using both PyPlot and @import matplotlib . .

**Comment by jmxpearson** [comment]
If you follow the instructions at the bottom of [the IJulia README](https://github.com/JuliaLang/IJulia.jl) to get debugging output, do you get something similar to stevengj/PyPlot.jl#167?

**Comment by ttfoley** [comment]
I used the verbose error and found that there was a problem with the way it was calling openblas (there was a missing 3?) .  As it stands, everything seems to work!  Quite the adventure. Thank you very much for the help!  I will be sure to use the verbose errors in the future to better debug.

**Comment by jmxpearson** [comment]
Great!

**Comment by stevengj** [comment]
@ttfoley, how did you solve the problem?

**Comment by ttfoley** [comment]
After checking the output as jmx suggested, I saw there was a bad call to 
liblapack.so.3

So I reinstalled all of the atlas stuff, and ran:
sudo update-alternatives --all
making sure the names matched.  

I am still using the "trick" of calling:
 LD_PRELOAD=/usr/lib/atlas-base/atlas/liblapack.so.3 ipython notebook

**Comment by dehann** [comment]
Hi, think I am having the same issue with liblapack and libopenblas. (I originally posted under stevengj/PyPlot.jl#140). Neither LD_PRELOAD or the conda update options have worked for me yet. I've tried:
```
LD_PRELOAD=/usr/lib/liblapack.so
LD_PRELOAD=${USER}/anaconda/lib/libopenblas.so
```
and
```
conda update conda
conda update anaconda
```
The easiest way for me to produce the problem is:
```
$ juliarc2
julia> using PyCall
julia> @pyimport numpy as np
```
at which point I consistently get import errors similar to
```
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('/home/dehann/anaconda/lib/python2.7/site-packages/numpy/linalg/lapack_lite.so: undefined symbol: zgelsd_',)
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg

 [inlined code] from /home/dehann/.julia/v0.4/PyCall/src/exception.jl:82
 in pyimport at /home/dehann/.julia/v0.4/PyCall/src/PyCall.jl:321
```
Maybe I'm still doing something different from the workarounds suggested here and at stevengj/PyPlot.jl#140. Maybe worth noting that I do not have atlas-base installed on this machine:
```
$ locate liblapack.so
/etc/alternatives/liblapack.so
/etc/alternatives/liblapack.so.3
/etc/alternatives/liblapack.so.3gf
/usr/lib/liblapack.so
/usr/lib/liblapack.so.3
/usr/lib/liblapack.so.3gf
/usr/lib/lapack/liblapack.so
/usr/lib/lapack/liblapack.so.3
/usr/lib/lapack/liblapack.so.3.0
/var/lib/dpkg/alternatives/liblapack.so
/var/lib/dpkg/alternatives/liblapack.so.3
```
and a sub-sampling of
```
$ locate libopenblas
/home/dehann/anaconda/lib/libopenblas.so
/home/dehann/anaconda/pkgs/openblas-0.2.14-1/lib/libopenblas.so
/usr/lib/libopenblas.so.0
/usr/lib/openblas-base/libopenblas.so.0
```
Lastly,
```
julia> Pkg.status("PyCall")
 - PyCall                        1.0.3
julia> versioninfo()
Julia Version 0.4.0-rc2
Commit fa52609* (2015-09-18 17:51 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3920XM CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
Maybe this info helps isolate the problem.

**Comment by stevengj** [comment]
@dehann, try preloading `/home/dehann/anaconda/lib/python2.7/site-packages/numpy/linalg/lapack_lite.so`, the library it is complaining about

**Comment by dehann** [comment]
@stevengj thanks, unfortunately not it. I think the problem is elsewhere. 
```
$ LD_PRELOAD=/home/dehann/anaconda/lib/python2.7/site-packages/numpy/linalg/lapack_lite.so
[and also for, $ /usr/lib/pyshared/python2.7/numpy/linalg/lapack_lite.so]
[and also for, $ /usr/lib/python2.7/dist-packages/numpy/linalg/lapack_lite.so]
$ juliarc2
julia> using PyCall

julia> @pyimport numpy as np
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('/home/dehann/anaconda/lib/python2.7/site-packages/numpy/linalg/lapack_lite.so: undefined symbol: zgelsd_',)
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/dehann/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg

 [inlined code] from /home/dehann/.julia/v0.4/PyCall/src/exception.jl:82
 in pyimport at /home/dehann/.julia/v0.4/PyCall/src/PyCall.jl:321
```

I'll search more. What's odd to me is that the only change was from Julia-dev+5933 to rc2. Will post again if I find any more details.

**Comment by jmxpearson** [comment]
I may be misreading your output, but `LD_PRELOAD=` needs to be on the same line as `juliarc2`. It only sets the variable for the command that follows.

**Comment by dehann** [comment]
Hi @jmxpearson @stevengj , the LD_PRELOAD path on the same line for lapack_lite worked thanks. I would have guessed LD_PRELOAD is an environment variable stable within a terminal session -- quite surprised it makes a difference when running on a new line. I'd rather not export LD_PRELOAD system wide (maybe just an alias for now). Don't know PyCall well enough to contribute on this yet, but will have a look in time. Thanks!

**Comment by jmxpearson** [comment]
Glad it worked!

**Comment by stevengj** [comment]
@dehann, if you just set `LD_PRELOAD=...`, that is not an environment variable, it is just a local variable in the shell.  To create a global environment variable in a session, do `export LD_PRELOAD=...` (in bash and similar) or `setenv LD_PRELOAD ...` (in csh and similar).    In contrast, if you do `LD_PRELOAD=... command ...`, that is the shell syntax to set an environment variable only when launching a particular process.

**Comment by dehann** [comment]
That makes sense, thanks.

**Comment by stevengj** [comment]
This should be fixed in Julia 0.4, which renamed `libopenblas`.

**Comment by holocronweaver** [comment]
I just tested with Julia 0.4rc4 and the problem presented by OP is still present on Ubuntu 15.04. Can import other Python packages into Julia OK, and can import and use numpy from within Python 2 without issue.

**Comment by stevengj** [comment]
@holocronweaver, are you building Julia from source?  Possibly you have `libopenblas.so` files lying around from previous Julia builds/installations....

**Comment by dehann** [comment]
Julia 0.4 on Ubuntu 12.04 (generic binaries) has solved the problem for me, thanks! The PRELOAD workaround no longer required on my current setup.

**Comment by holocronweaver** [comment]
@stevengj That was indeed the issue! I ran `git clean -xdf` followed by `make` and now `@pyimport numpy` runs fine.

**Comment by quasitam** [comment]
I found this thread as I had a similar problem on a vanilla machine in a controlled python/python-package environment which I have resolved, thanks to some of the tips and hints in this thread, so I am sharing my solution.

My error was initially:
```
numpy/lib/__init__.py:17: in <module>
from . import scimath as emath
ImportError: cannot import name scimath
```

In a different configuration it also manifested as
```
File "./../numpy-1.9.2-py2.7-linux-x86_64.egg/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "./../numpy-1.9.2-py2.7-linux-x86_64.egg/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
```

I used the LD_PRELOAD tip above for lapack_lite.so (equivalent to adding the location of lapack_lite.so to the LD_LIBRARY_PATH) and these both also gave the error 
```
ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
```

On the one machine I have where it does work turns out I had "atlas" installed which contained
```
find /usr -name liblapack.so.3
/usr/lib64/atlas/liblapack.so.3
```

So you need to get this library and add it to the LD_LIBRARY_PATH before executing python (eg through atlas or other means).
There may be further depenciies beyond liblapack.so.3 but that is certainly the cause of this error.

**Comment by maximsch2** [comment]
@stevengj,
It looks like Julia 0.4 from https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases is using libopenblas.so on Ubuntu 14.04 (at least that's what it is installing and I'm getting the same problem). Building Julia from source works just fine though

**Comment by stevengj** [comment]
@staticfloat, is there anything that can be done about the Ubuntu package?

**Comment by staticfloat** [comment]
@stevengj I've tried to follow the conversation here but I'm having a little trouble. What is the fix that is needed?  When running on Ubuntu 14.04, with the following packages installed:

```
$ dpkg -s julia | grep Version
Version: 0.4.1-trusty1
$ dpkg -s libopenblas-base | grep Version
Version: 0.2.10.1-trusty2
```

Everything works just fine, as far as I can tell:

```
$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.1 (2015-11-08 10:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
|__/                   |  x86_64-linux-gnu

julia> using PyCall

julia> @pyimport numpy

julia>
```

**Comment by staticfloat** [comment]
A little bit more information:

```
julia> filter(x -> contains(x,"blas"), Libdl.dllist())
1-element Array{AbstractString,1}:
 "/usr/lib/libopenblas.so.0"

julia> filter(x -> contains(x,"numpy"), Libdl.dllist())
8-element Array{AbstractString,1}:
 "/usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.so"
 "/usr/local/lib/python2.7/dist-packages/numpy/core/umath.so"
 "/usr/local/lib/python2.7/dist-packages/numpy/core/scalarmath.so"
 "/usr/local/lib/python2.7/dist-packages/numpy/lib/_compiled_base.so"
 "/usr/local/lib/python2.7/dist-packages/numpy/linalg/lapack_lite.so"
 "/usr/local/lib/python2.7/dist-packages/numpy/linalg/_umath_linalg.so"
 "/usr/local/lib/python2.7/dist-packages/numpy/fft/fftpack_lite.so"
 "/usr/local/lib/python2.7/dist-packages/numpy/random/mtrand.so"
```

**Comment by stevengj** [comment]
@staticfloat, it seems like you are not using the Ubuntu numpy package, which would normally be in `/usr/lib` rather than `/usr/local/lib`?

**Comment by staticfloat** [comment]
Ah, you are correct, I installed numpy from source.  I'll try installing the package and see what happens.

**Comment by staticfloat** [comment]
Even after installing the debian package and removing everything in `/usr/local/lib/python2.7/dist-packages/numpy`  things work the same as before.

**Comment by maximsch2** [comment]
I'm using Python from Anaconda if that matters.

**Comment by maximsch2** [comment]
OK, we've talked a bit more with @staticfloat and here is what we found:

1) Julia on Ubuntu is using system `libopenblas` (not renamed), while loading extra symbols from `liblapack.so` (LAPACK is not built in OpenBlas)
2) Latest version of Numpy in Anaconda loads `libopenblas` (provided by Anaconda as well) and expects to find LAPACK symbols there.

So when I try to import Anaconda-provided version of NumPy through PyCall, it fails to find needed LAPACK symbol ("zgelsd_") because `libopenblas` is already loaded (Ubuntu's version) and it doesn't export symbols that NumPy expects.

Solutions:
1) Using Julia built from source works, because then `libopenblas` is renamed.
2) Doing LD_PRELOAD=`anaconda/lib/libopenblas.so` works as well (Anaconda's version of OpenBlas is a superset of system version)
3) Interestingly, this thing also works:
```julia
Libdl.dlopen("/usr/lib/liblapack.so.3", Libdl.RTLD_GLOBAL)

using PyCall
@pyimport numpy
```
This way, NumPy is loading needed LAPACK symbols from Ubuntu's `liblapack.so` (that is already loaded by Julia btw, but for some reason symbols are not available to NumPy without that extra `Libdl.dlopen`)

**Comment by staticfloat** [comment]
@stevengj Do you think there is a way we can auto-detect condition and load `liblapack` into the global namespace automatically?  Alternatively, should we be loading `liblapack` into the global namespace automatically anyway?  I believe this is the default on OSX but perhaps not on Linux.

**Comment by stevengj** [comment]
@staticfloat, on most systems the Julia binaries load the ILP64 `libopenblas64_.so` and all the symbols are suffixed with `64_`, so they are not visible at all to other libraries like numpy that want to link the ordinary LP64 blas/lapack.

The problems arise when both numpy and julia both want to link to a library called `libopenblas.so`, but numpy is expecting different library contents.

**Comment by staticfloat** [comment]
That is one problem.  This problem is slightly different.

OpenBLAS has an option to statically build LAPACK and embed LAPACK within it; thereby creating a single .so file (`libopenblas.so`) that contains both the BLAS and LAPACK symbols.  Anaconda's `libopenblas.so` does this, the default Ubuntu/Debian packages do not so as to maintain a weak linking between BLAS and LAPACK.  (Apparently, in ages long lost to the mists of time, there were developers that wanted to experiment with different pairings of BLAS and LAPACK libraries).  None of this is a problem until Julia attempts to load `numpy`, which has shared libraries that have an explicit dependence on `libopenblas` but not `liblapack`.  Because a library called `libopenblas.so` is already linked into the current process, we don't attempt to `dlopen()` Anaconda's `libopenblas.so`.  This is not a problem in general however, because as long as there is not a mixup of ILP64 symbols we shouldn't have any lacking symbols.  (There is no mixup in this case because both the ubuntu `libopenblas` package and Anaconda's `libopenblas` are non-ILP64)

The issue arises because `numpy` expects to get LAPACK symbols from `libopenblas.so`; not that it is explicitly searching for the symbols in that particular file, but that it does not declare a dependency on `liblapack.so`.  I originally thought this would not be a problem, as Julia already has `liblapack.so` mapped into its address space, so searching for symbols like `zgelsd_` (the actual culprit in @maximsch2's case above) should have  been resolvable, but it turns out that `liblapack.so` is loaded without the `RTLD_GLOBAL` flag by default, thereby limiting its visibility to external libraries.  I'm not sure about the rationale behind this design, and I get the sinking feeling that it is platform-dependent (e.g. I think this would not be the case on OS X) but regardless, the fact that simply explicitly loading `liblapack.so` into the global namespace (Which is what @maximsch2's `dlopen()` above does) works shows that a "reasonable" fix should exist.

**Comment by tkelman** [comment]
Back in the day Atlas etc didn't contain any lapack implementation pieces, so you could keep the netlib reference lapack and just swap out libblas dynamically and still get a speedup. MKL typically put blas and lapack into the same library but is not open source so linux distributions didn't really accomodate it here. Open source implementations that follow the mkl organization of having everything in the same library are a bit newer and distros haven't really caught up yet.

Always dlopening liblapack on linux, or maybe only when lapack_name doesn't match blas_name, would make sense here. SCS.jl has been doing so.

**Comment by staticfloat** [comment]
I guess my question is why isn't `liblapack` opened with `RTLD_GLOBAL` in the first place?  What is the use case for that state of affairs?

**Comment by tkelman** [comment]
Guessing, but probably because the name/ILP64 conflicts used to be an issue, and it hasn't been adjusted since that was rectified?

**Comment by tkelman** [comment]
I don't know what the numbers look like on openblas' lapack vs netlib lapack linked against openblas for just libblas, but we could raise this with anaconda and see whether it would make sense for them to build blas-only openblas the way ubuntu is doing?

**Comment by staticfloat** [comment]
I don't think there's any reason to do that; in fact, we build openblas-with-lapack when we do a from-source build.

**Comment by tkelman** [comment]
Right, but we also do ILP64 and tend to err on the side of performance over compatibility in source builds and tarball binaries. Anaconda doesn't do ILP64 and may care more strongly about compatibility than we do.

**Comment by maximsch2** [comment]
One solution here would be to get Julia into Anaconda and then just tell people like me that they should install Julia from Anaconda as well if they want it to play nicely with Anaconda's Python. Right now I can see Julia there in some 3rd party channels, but none of them has 0.4.1 or even a release version of 0.4.0.

**Comment by tkelman** [comment]
Maybe. There are several ways of going about that, some of which would be much more challenging than others. Another option is for you to use the tarball binaries of Julia rather than the Ubuntu PPA, which would be more isolated in terms of library naming.

**Comment by maximsch2** [comment]
Right. Right now I've switched to building Julia from source, so I don't really have an issue on my end. This is more about what to do when someone else runs into the same setup (Julia package from PPA + Anaconda)

**Comment by stevengj** [comment]
If we are linking to the system LP64 blas and lapack, I think we should load them with RTLD_GLOBAL.  If we are linking to our own ILP64 openblas+lapack, it doesn't matter because the symbols are suffixed with `64_`.

**Comment by stevengj** [comment]
@staticfloat, would it be enough to add:
```jl
    if startswith(basename(Base.liblapack_name), "liblapack")
        Libdl.dlopen(Base.liblapack_name, Libdl.RTLD_LAZY|Libdl.RTLD_DEEPBIND|Libdl.RTLD_GLOBAL)
    end
```
to PyCall's `__init__` function?

**Comment by staticfloat** [comment]
@maximsch2 could you try putting the following snippet just below [this line](https://github.com/stevengj/PyCall.jl/blob/6ed6fa99251eca5299b70b27560e15af858e2450/src/pyinit.jl#L30) in `PyCall/src/pyinit.jl`:

```julia
    if basename(Base.liblapack_name) != basename(Base.libblas_name)
        Libdl.dlopen(Base.liblapack_name, Libdl.RTLD_LAZY|Libdl.RTLD_DEEPBIND|Libdl.RTLD_GLOBAL)
    end
```
